version: "3"

tasks:
  build:
    cmds:
      - go build -v -o main main.go
    sources:
      - configs/**/*
      - controllers/**/*
      - middleware/**/*
      - models/**/*
      - routes/**/*
      - utils/**/*
  default:
    cmds:
      - task: build
      - ./main
